#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 14 18:35:12 ART 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryShaders_v4.7.1.zip
enableShaders=false
